# Generated by Django 5.1.2 on 2024-11-20 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 10, 25, 2, 692745, tzinfo=datetime.timezone.utc)),
        ),
    ]
