# Generated by Django 5.1.2 on 2024-11-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 8, 47, 2, 104218, tzinfo=datetime.timezone.utc)),
        ),
    ]
