# Generated by Django 5.1.2 on 2024-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('C', 'Customer')], default='C', max_length=1),
        ),
    ]
