# Generated by Django 5.1.2 on 2024-11-07 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_routestation_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routestation',
            name='unique_station_per_route',
        ),
        migrations.RemoveConstraint(
            model_name='routestation',
            name='unique_order_per_route',
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 15, 26, 17, 482710, tzinfo=datetime.timezone.utc)),
        ),
    ]
